# Default initial positions for dynaarm's ros2_control fake system

initial_positions:
  arm_left/elbow_flexion: 0
  arm_left/forearm_rotation: 0
  arm_left/shoulder_flexion: 0
  arm_left/shoulder_rotation: 0
  arm_left/wrist_flexion: 0
  arm_left/wrist_rotation: 0
  arm_right/elbow_flexion: 0
  arm_right/forearm_rotation: 0
  arm_right/shoulder_flexion: 0
  arm_right/shoulder_rotation: 0
  arm_right/wrist_flexion: 0
  arm_right/wrist_rotation: 0
