# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller_arm_1
    - joint_trajectory_controller_arm_2

  joint_trajectory_controller_arm_1:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - arm_left/shoulder_rotation
      - arm_left/shoulder_flexion
      - arm_left/elbow_flexion
      - arm_left/forearm_rotation
      - arm_left/wrist_flexion
      - arm_left/wrist_rotation
  joint_trajectory_controller_arm_2:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - arm_right/shoulder_rotation
      - arm_right/shoulder_flexion
      - arm_right/elbow_flexion
      - arm_right/forearm_rotation
      - arm_right/wrist_flexion
      - arm_right/wrist_rotation
