controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    dynaarm_status_broadcaster_arm_1:
      type: dynaarm_controllers/StatusBroadcaster

    gravity_compensation_controller_arm_1:
      type: dynaarm_controllers/GravityCompensationController

    freedrive_controller_arm_1:
      type: dynaarm_controllers/FreeDriveController

    joint_trajectory_controller_arm_1:
      type: joint_trajectory_controller/JointTrajectoryController

    freeze_controller_arm_1:
      type: dynaarm_controllers/FreezeController

    dynaarm_status_broadcaster_arm_2:
      type: dynaarm_controllers/StatusBroadcaster

    gravity_compensation_controller_arm_2:
      type: dynaarm_controllers/GravityCompensationController

    freedrive_controller_arm_2:
      type: dynaarm_controllers/FreeDriveController

    joint_trajectory_controller_arm_2:
      type: joint_trajectory_controller/JointTrajectoryController

    freeze_controller_arm_2:
      type: dynaarm_controllers/FreezeController

freeze_controller_arm_1:
  ros__parameters:
    arm_name: arm_1/DynaarmSystem

freeze_controller_arm_2:
  ros__parameters:
    arm_name: arm_2/DynaarmSystem

dynaarm_status_broadcaster_arm_1:
  ros__parameters:
    joints:
      - arm_left/shoulder_rotation
      - arm_left/shoulder_flexion
      - arm_left/elbow_flexion
      - arm_left/forearm_rotation
      - arm_left/wrist_flexion
      - arm_left/wrist_rotation

joint_trajectory_controller_arm_1:
  ros__parameters:
    joints:
      - arm_left/shoulder_rotation
      - arm_left/shoulder_flexion
      - arm_left/elbow_flexion
      - arm_left/forearm_rotation
      - arm_left/wrist_flexion
      - arm_left/wrist_rotation
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    # See https://control.ros.org/jazzy/doc/ros2_controllers/joint_trajectory_controller/doc/parameters.html for a full list of all parameters
    allow_partial_joints_goal: false # trajectory needs to contain goals from all joints handled by the controller
    constraints:
      stopped_velocity_tolerance: 0.5
      goal_time: 0.05
      # Tolerances for each joint
      arm_left/shoulder_rotation: { trajectory: 0.5, goal: 0.05 }
      arm_left/shoulder_flexion: { trajectory: 0.5, goal: 0.05 }
      arm_left/elbow_flexion: { trajectory: 0.5, goal: 0.05 }
      arm_left/forearm_rotation: { trajectory: 0.5, goal: 0.05 }
      arm_left/wrist_flexion: { trajectory: 0.5, goal: 0.05 }
      arm_left/wrist_rotation: { trajectory: 0.5, goal: 0.05 }


gravity_compensation_controller_arm_1:
  ros__parameters:
    joints:
      - arm_left/shoulder_rotation
      - arm_left/shoulder_flexion
      - arm_left/elbow_flexion
      - arm_left/forearm_rotation
      - arm_left/wrist_flexion
      - arm_left/wrist_rotation

freedrive_controller_arm_1:
  ros__parameters:
    joints:
      - arm_left/shoulder_rotation
      - arm_left/shoulder_flexion
      - arm_left/elbow_flexion
      - arm_left/forearm_rotation
      - arm_left/wrist_flexion
      - arm_left/wrist_rotation




dynaarm_status_broadcaster_arm_2:
  ros__parameters:
    joints:
      - arm_right/shoulder_rotation
      - arm_right/shoulder_flexion
      - arm_right/elbow_flexion
      - arm_right/forearm_rotation
      - arm_right/wrist_flexion
      - arm_right/wrist_rotation

joint_trajectory_controller_arm_2:
  ros__parameters:
    joints:
      - arm_right/shoulder_rotation
      - arm_right/shoulder_flexion
      - arm_right/elbow_flexion
      - arm_right/forearm_rotation
      - arm_right/wrist_flexion
      - arm_right/wrist_rotation
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    # See https://control.ros.org/jazzy/doc/ros2_controllers/joint_trajectory_controller/doc/parameters.html for a full list of all parameters
    allow_partial_joints_goal: false # trajectory needs to contain goals from all joints handled by the controller
    constraints:
      stopped_velocity_tolerance: 0.5
      goal_time: 0.05
      # Tolerances for each joint
      arm_right/shoulder_rotation: { trajectory: 0.5, goal: 0.05 }
      arm_right/shoulder_flexion: { trajectory: 0.5, goal: 0.05 }
      arm_right/elbow_flexion: { trajectory: 0.5, goal: 0.05 }
      arm_right/forearm_rotation: { trajectory: 0.5, goal: 0.05 }
      arm_right/wrist_flexion: { trajectory: 0.5, goal: 0.05 }
      arm_right/wrist_rotation: { trajectory: 0.5, goal: 0.05 }


gravity_compensation_controller_arm_2:
  ros__parameters:
    joints:
      - arm_right/shoulder_rotation
      - arm_right/shoulder_flexion
      - arm_right/elbow_flexion
      - arm_right/forearm_rotation
      - arm_right/wrist_flexion
      - arm_right/wrist_rotation

freedrive_controller_arm_2:
  ros__parameters:
    joints:
      - arm_right/shoulder_rotation
      - arm_right/shoulder_flexion
      - arm_right/elbow_flexion
      - arm_right/forearm_rotation
      - arm_right/wrist_flexion
      - arm_right/wrist_rotation
