# Default initial positions for dynaarm's ros2_control fake system

initial_positions:
  elbow_flexion: 0
  forearm_rotation: 0
  shoulder_flexion: 0
  shoulder_rotation: 0
  wrist_flexion: 0
  wrist_rotation: 0
